#spring boot配置
spring:
  application.name: fundprod
  datasource:
    url: jdbc:mysql://localhost:3306/av?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234567890
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 20
    max-idle: 10
    testOnBorrow: true
    validationQuery: SZELECT 1


#文件下载重试次数
file.retry.times: 5
#爬虫线程数
spider.thread:  5

#桃花族网站
site:
#域名
  domain: thzbbt.net
#超时时间(ms)
  timeout:  300000
#休眠时间(ms)
  sleep.time: 5000
  #文件保存路径
file.save.dir: "D:/TaoHuaZu"

#DMM网站
dmm:
  site:
    #域名
    domain: www.dmm.co.jp
    #超时时间(ms)
    timeout:  300000
    #休眠时间(ms)
    sleep.time: 5000
  #文件保存路径
  file.save.dir: "D:/DMM"

